spring.application.name=Example
server.port=8081
# spring.datasource.url = jdbc:sqlserver://localhost:50202;trustServerCertificate=true;encrypt=true;integratedSecurity=false;databaseName=HardwareWebShop;
# spring.datasource.username = hardware
# spring.datasource.password = hardware
spring.datasource.url = jdbc:h2:mem:testdb
spring.datasource.driverClassName = org.h2.Driver
spring.datasource.username = sa
spring.datasource.password = password
spring.jpa.database-platform = org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization = true